version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-laravel9-app-1
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./nginx/default.conf:/etc/nginx/sites-available/default
    networks:
      - laravel9

  nginx:
    image: nginx:alpine
    container_name: docker-laravel9-nginx-1
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel9

networks:
  laravel9:
    driver: bridge
